-- Run as: waystone_load
\set ON_ERROR_STOP on

CREATE TABLE IF NOT EXISTS ref.strategy (
    strategy_id          smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_code        text NOT NULL UNIQUE CHECK (strategy_code ~ '^[a-z][a-z0-9_]{1,47}$'),
    display_name         text NOT NULL,
    asset_class          text NOT NULL CHECK (asset_class IN ('future', 'option')),
    instrument_root      text NOT NULL,
    registry_algo_id     text,
    gcs_paper_prefix     text NOT NULL,
    gcs_backtest_prefix  text,
    backtest_file_prefix text,
    broker_account       text,
    broker_client_id     integer,
    paper_start_date     date,
    is_active            boolean NOT NULL DEFAULT true,
    notes                text,
    created_at           timestamptz NOT NULL DEFAULT now()
);

-- One row per settings change; the loader uses the row with the latest valid_from <= session_date.
CREATE TABLE IF NOT EXISTS ref.strategy_settings (
    strategy_id                smallint NOT NULL REFERENCES ref.strategy,
    valid_from                 date NOT NULL,
    starting_capital           numeric(14, 2) NOT NULL,
    point_value                numeric(12, 4) NOT NULL,
    tick_size                  numeric(10, 4),
    default_contracts          integer NOT NULL,
    commission_rt_per_contract numeric(10, 4) NOT NULL,
    model_slip_rt_per_contract numeric(10, 4) NOT NULL,
    session_minutes            integer NOT NULL,
    session_roll_hour          smallint NOT NULL CHECK (session_roll_hour BETWEEN 0 AND 23),
    flatten_time               time,
    daily_loss_cap             numeric(12, 2),
    max_trades_per_day         integer,
    risk_free_rate             numeric(8, 6) NOT NULL DEFAULT 0,
    ann_days                   smallint NOT NULL DEFAULT 252,
    min_days_ratio             smallint NOT NULL DEFAULT 5,
    min_days_calmar            smallint NOT NULL DEFAULT 21,
    sync_pct_threshold         numeric(6, 4) NOT NULL DEFAULT 0.15,
    sync_usd_floor             numeric(12, 2) NOT NULL DEFAULT 0,
    expected_bar_count         integer,
    notes                      text,
    PRIMARY KEY (strategy_id, valid_from)
);

CREATE TABLE IF NOT EXISTS ref.strategy_config (
    strategy_id     smallint NOT NULL REFERENCES ref.strategy,
    params_fp       text NOT NULL,
    config_label    text,
    params          jsonb,
    first_seen_date date,
    last_seen_date  date,
    PRIMARY KEY (strategy_id, params_fp)
);

CREATE TABLE IF NOT EXISTS ref.instrument (
    instrument_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol            text NOT NULL UNIQUE,
    root              text NOT NULL,
    asset_class       text NOT NULL CHECK (asset_class IN ('future', 'option', 'stock', 'index')),
    exchange          text,
    multiplier        numeric(12, 4),
    expiry            date,
    strike            numeric(14, 4),
    opt_right         char(1) CHECK (opt_right IN ('C', 'P')),
    underlying_symbol text,
    broker_conid      bigint UNIQUE
);

CREATE TABLE IF NOT EXISTS ref.trading_holiday (
    exchange     text NOT NULL,
    holiday_date date NOT NULL,
    name         text NOT NULL,
    PRIMARY KEY (exchange, holiday_date)
);

CREATE TABLE IF NOT EXISTS ref.kpi_definition (
    kpi_code     text PRIMARY KEY,
    asset_class  text NOT NULL CHECK (asset_class IN ('future', 'option', 'any')),
    section      text NOT NULL,
    section_name text NOT NULL,
    label        text NOT NULL,
    description  text,
    direction    text CHECK (direction IN ('Higher', 'Lower')),
    green_at     numeric,
    amber_at     numeric,
    unit         text,
    source       text CHECK (source IN ('COMPUTED', 'DERIVED', 'MANUAL')),
    is_critical  boolean NOT NULL DEFAULT false,
    sort_order   integer NOT NULL
);

-- Fixed research figures (the workbook's BT tabs and the scorecard "Backtest ref." column).
CREATE TABLE IF NOT EXISTS ref.backtest_reference (
    strategy_id smallint NOT NULL REFERENCES ref.strategy,
    ref_key     text NOT NULL,
    num_value   numeric,
    text_value  text,
    source_doc  text,
    as_of       date,
    PRIMARY KEY (strategy_id, ref_key)
);
